version: '2'
services:
  app:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - 8080:3000
    volumes:
      - '.:/service'
      - '/service/node_modules'
    command: yarn start:dev

  redis:
    image: redis
    expose:
      - "6379"
